import {  Open_Sans } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { ToastProvider } from "@/components/UserToast";

const openSans = Open_Sans({
 subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], 
  variable: "--font-open-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans antialiased`}>
         <ReduxProvider>
       <ToastProvider> {children}</ToastProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
